name: myfirst
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello world"
      - name: Print GoodBye
        run: echo "Done-bye"
      - name: Run multiple commands
        run: | 
            echo "first line"
            echo "second line"
    
